### ISSUE TITLE
"Classic NES Series - Zelda II" fails to start

### ISSUE THREAD

**Issue by SapphireTactician** [libretro/beetle-gba-libretro#24]
### Description:

When using `Classic NES Series - Zelda II` from the "No Intro" set with the Beetle GBA core, the game fails to start successfully, presenting an in-game error message saying "Game Pak Error   Turn the Power Off." Game loads and plays fine on the other GBA cores except for Meteor GBA.

This bug occurs both with and without HLE. GBA bios file is present.

*****

### Specs:

**CPU:** AMD Athlon II X2 250 Dual Core  

**GPU:** NVIDIA GeForce 6150SE  

**RAM:** 8 GB  

**OS:** Debian 9 (_Stretch_) x86_64 Stable  

**RetroArch Version:** 1.7.2

**Beetle GBA Core Commit Version:** v0.9.36 c9acdca

-------

### Expected Behavior:

Game should be able to play normally.  

-------

### Actual Behavior:

Game boots to the following error message: `GAME PAK ERROR   TURN THE POWER OFF.`

![2018-04-21--182038_1600x900](https://user-images.githubusercontent.com/24427487/39089332-8e1eb20c-4592-11e8-9e2f-73628ae329e0.png)

-------

### Steps to Reproduce:

* Load Core
    * Select `Nintendo - GameBoy Advance (Beetle GBA)`
* Load Content
    * Load Classic NES Series - Zelda II

-------

### Additional Research / Reading Material:

Apparently, according to this blog entry ( https://mgba.io/2014/12/28/classic-nes/ ) the Classic NES series of games possess anti-emulation features. The blog belongs to mGBA's official site. It should prove useful in resolving this.

**Comment by retro-wertz** [comment]
the core currently does not support internal database for these type of games(super mario advace 4 is one of them). its still using the mednafen-style of detecting save ram type/size etc. use other gba atm or if you prefer using this core, refer to mednafen doc on how to use gba ."type" format (since i format how it was suppose to be layout(ed) when i worked on this core before.

**Comment by retro-wertz** [comment]
this should be fixed in latest commit...
